FROM python:3.10

WORKDIR /workspace

COPY requirements.txt .

# Installa dipendenze Python
RUN pip install --no-cache-dir -r requirements.txt



COPY . .

ENV PYTHONPATH=/workspace/src:$PYTHONPATH
ENV OPENBLAS_NUM_THREADS=1
ENV OMP_NUM_THREADS=1

CMD ["bash"]
