FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# ---- Install system dependencies and Miniconda ----
RUN apt-get update && apt-get install -y \
    wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p $CONDA_DIR && \
    rm /tmp/miniconda.sh && \
    $CONDA_DIR/bin/conda clean -t -i -p -y && \
    ln -s $CONDA_DIR/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.bashrc

# ---- Set working directory ----
WORKDIR /workspace

# ---- Copy source code ----
COPY . /workspace/

# ---- Accept Conda Terms of Service ----
RUN $CONDA_DIR/bin/conda config --set always_yes yes && \
    $CONDA_DIR/bin/conda config --set report_errors true && \
    $CONDA_DIR/bin/conda tos accept --channel https://repo.anaconda.com/pkgs/main && \
    $CONDA_DIR/bin/conda tos accept --channel https://repo.anaconda.com/pkgs/r && \
    $CONDA_DIR/bin/conda create -n myenv python=3.10 -y && \
    $CONDA_DIR/envs/myenv/bin/pip install --upgrade pip && \
    $CONDA_DIR/envs/myenv/bin/pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu118 && \
    $CONDA_DIR/envs/myenv/bin/pip install pynever jinja2 pandas multipledispatch



# ---- Set environment variables ----
ENV PYTHONPATH=/workspace

# ---- Use conda run as entrypoint ----
CMD ["bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate myenv && exec bash"]
