general:
  device: cpu
  seed: 100

  enable_incomplete_verification: false
  complete_verifier: bab

  results_file: out.txt
  output_file: out.pkl

model:
  onnx_path: "/mnt/c/Users/andr3/PycharmProjects/TripleAIPaper/verification_time_testing/verificatori/alpha_beta_crown/networks/FC/0.03/100.onnx"


specification:
  type: lp
  vnnlib_path: "/mnt/c/Users/andr3/PycharmProjects/TripleAIPaper/verification_time_testing/verificatori/alpha_beta_crown/properties/0.03/sample_0019_label_4_eps_0.030.vnnlib"
  norm: .inf