FROM continuumio/miniconda3

# Crea e configura l'ambiente conda
RUN conda create -n myenv python=3.10 pip -y && \
    conda clean -afy

# Usa sempre l'ambiente myenv
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

# Installa git e dipendenze di sistema
RUN apt-get update && apt-get install -y git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Installa PyTorch (CUDA 11.8)
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# Installa pacchetti extra
RUN pip install jinja2 pandas

# Copia i file del progetto
COPY . /workspace
WORKDIR /workspace

# Installa requirements del progetto
RUN pip install -r complete_verifier/requirements.txt

# Clona e installa auto_LiRPA su un commit specifico
RUN git clone https://github.com/Verified-Intelligence/auto_LiRPA && \
    cd auto_LiRPA && \
    git checkout 77e3c2b45c2b9c4e2462f6c070982e29b42cc0f5 && \
    pip install .


# Avvia bash di default
CMD ["bash"]
