general:
  device: gpu
  seed: 100
  enable_incomplete_verification: false
  complete_verifier: bab-refine

  results_file: out.txt
  output_file: out.pkl

model:
  onnx_path: "{{ onnx_path }}"

specification:
  vnnlib_path: "{{ vnnlib_path }}"
  norm: .inf

solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
  mip:
    parallel_solvers: 16
    refine_neuron_time_percentage: 0.8

bab:
  timeout: 300
  branching:
    reduceop: max

attack:
  pgd_order: after
